### ISSUE TITLE
Can't install from composer

### ISSUE THREAD

**Issue by eBusinessAtlantique** [yireo/Yireo_Webp2ForAmastyShopby#4]
Hello, It seems that it can't be installed from composer with composer require yireo/magento2-webp2-for-amasty-shopby

**Comment by jissereitsma** [comment]
Thanks. The composer package was actually available, but only as a `dev` version (so minimum stability in your composer would need to be changed). I have now released 0.0.1 (as it was mentioned in the module its `composer.json` file). Thanks for posting this issue!

**Comment by eBusinessAtlantique** [comment]
Thank you for the fast answer.
I got this error now :
  Problem 1
    - Root composer.json requires yireo/magento2-webp2-for-amasty-shopby * -> satisfiable by yireo/magento2-webp2-for-amasty-shopby[0.0.1].
    - yireo/magento2-webp2-for-amasty-shopby 0.0.1 requires yireo/magento2-webp2 ^0.10 -> found yireo/magento2-webp2[0.10.0, ..., 0.10.11] but it conflicts with your root composer.json require (^0.12.4).

**Comment by jissereitsma** [comment]
I see, this should now be fixed with version 0.0.2.

**Comment by eBusinessAtlantique** [comment]
Great, thanks
